const state={token:'',collection:'',cards:[],selected:null,compare:new Set(),details:new Map(),tasks:[],activeTasks:null,compareData:null,compareDim:'',mapData:null,libMode:'rail',aiLocked:false};
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const text=value=>esc(value).replace(/\n/g,'<br>');
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json','X-Research-Session':state.token,...(options.headers||{})}});let data=null;try{data=await r.json()}catch{data=null}if(!r.ok||data===null)throw new Error((data&&data.error)||`服务响应超时或异常（${r.status}），任务可能仍在后台进行。`);return data}
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3000)}
function dateLabel(value){if(!value)return '尚未生成';const [year,month,day]=value.split('-').map(Number);return `${year} 年 ${month} 月 ${day} 日`}
function connection(ok,label){$('zoteroDot').classList.toggle('ok',ok);$('connectionText').textContent=label;$('zoteroStatusDot').classList.toggle('green',ok);$('zoteroStatusLabel').textContent=label}
async function boot(){try{state.token=(await fetch('/api/session').then(r=>r.json())).token;loadDaily();const data=await api('/api/collections'),last=localStorage.getItem('researchCollection');state.collection=data.collections.includes(last)?last:(data.collections.includes('framing')?'framing':data.collections[0]||'');$('collectionSelect').innerHTML=data.collections.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');$('collectionSelect').value=state.collection;await loadCards();connection(true,'Zotero 与本地卡片已连接');refreshTasks()}catch(e){connection(false,'本地资料读取失败');toast(e.message)}loadSettings()}
async function loadCards(){const d=await api(`/api/cards?${new URLSearchParams({collection:state.collection,q:$('searchInput').value,status:$('statusFilter').value})}`);state.cards=d.cards;const built=d.cards.filter(x=>x.has_card);$('cardCount').textContent=built.length;$('railCount').textContent=`${built.length} 张精读 · ${d.cards.length-built.length} 待处理`;$('questionCount').textContent='0';renderList();if(!state.selected||!d.cards.some(x=>x.citekey===state.selected))state.selected=d.cards[0]?.citekey||null;if(state.selected){const p=d.cards.find(x=>x.citekey===state.selected);p.has_card?loadDetail(p.citekey):renderUnbuilt(p)}}
function authorsLine(m){const a=m.authors||[];return a.length>3?`${a.slice(0,3).join('、')} 等`:a.join('、')}
function yearOf(m){return (m.date||'').slice(0,4)}
function tagChips(p,limit){const en=p.enrichment||{},zt=(p.paper_meta||{}).tags||[];const tags=[...new Set([...(en.tags||[]),...zt])].slice(0,limit||4);return tags.map(t=>`<span class="mini-tag">${esc(t)}</span>`).join('')}
function selectedCards(){return state.cards.filter(p=>state.compare.has(p.citekey))}
function updateSelectionCounts(){const sel=selectedCards();$('compareCount').textContent=sel.filter(p=>p.has_card).length;$('enrichCount').textContent=sel.length;$('batchCount').textContent=sel.filter(p=>!p.has_card).length;$('selectAllPapers').textContent=sel.length&&sel.length===state.cards.length?'清空选择':'全选'}
function metaBlock(p){const m=p.paper_meta||{},en=p.enrichment||{},v=m.venue_meta||{};const rows=[];
if(m.authors?.length)rows.push(['作者',esc(authorsLine(m))]);
const published=[m.date,m.journal].filter(Boolean).join(' · ');if(published)rows.push(['发表',esc(published)]);
const metric=[v.if_2025?`IF ${v.if_2025}`:'',v.rank||'',v.group||''].filter(Boolean).join(' · ');if(metric)rows.push(['期刊指标',esc(metric)]);
if(m.doi)rows.push(['DOI',`<a href="https://doi.org/${esc(m.doi)}" target="_blank" rel="noopener">${esc(m.doi)}</a>`]);
if(en.keywords?.length)rows.push(['关键词',esc(en.keywords.join('、'))]);
if(en.method)rows.push(['方法',esc(en.method)]);
if(en.theory)rows.push(['理论',esc(en.theory)]);
const tags=tagChips(p,8);
const quick=en.quick_take?`<p class="meta-quick">${text(en.quick_take)}</p>`:'';
const zh=en.abstract_zh?`<details class="meta-abstract" open><summary>中文摘要（AI 翻译）</summary><p>${text(en.abstract_zh)}</p></details>`:'';
const original=m.abstract?`<details class="meta-abstract"><summary>摘要原文</summary><p>${text(m.abstract)}</p></details>`:'';
const hint=en.generated_at?'':'<p class="muted meta-hint">在左侧勾选论文后点「AI 标签·翻译」，可生成中文摘要、关键词与研究标签。</p>';
if(!rows.length&&!tags&&!quick&&!zh&&!original)return '';
return `<div class="meta-block">${rows.length?`<dl>${rows.map(([k,v2])=>`<div><dt>${k}</dt><dd>${v2}</dd></div>`).join('')}</dl>`:''}${tags?`<div class="meta-tags">${tags}</div>`:''}${quick}${zh}${original}${hint}</div>`}
function renderList(){if(!state.cards.length){$('paperList').innerHTML='<p class="muted">当前筛选没有论文。</p>';updateSelectionCounts();return}
$('paperList').innerHTML=state.cards.map(p=>{const m=p.paper_meta||{},v=m.venue_meta||{};const meta=[authorsLine(m),[yearOf(m),m.journal].filter(Boolean).join(' · ')].filter(Boolean).join(' ｜ ');const badge=[v.if_2025?`IF ${v.if_2025}`:'',v.rank||''].filter(Boolean).join(' · ');
return `<button class="paper-item ${p.citekey===state.selected?'active':''}" data-key="${esc(p.citekey)}"><input class="paper-check" type="checkbox" data-compare="${esc(p.citekey)}" aria-label="选择论文：${esc(p.title)}" ${state.compare.has(p.citekey)?'checked':''}><strong>${esc(p.title)}</strong>${meta?`<span class="item-meta">${esc(meta)}</span>`:`<small>${esc(p.citekey)}</small>`}${badge?`<span class="item-if">${esc(badge)}</span>`:''}${tagChips(p,3)?`<span class="item-tags">${tagChips(p,3)}</span>`:''}<span class="status-pill">${p.has_card?'已有精读卡':'未精读'}</span></button>`}).join('');
document.querySelectorAll('.paper-item').forEach(b=>b.addEventListener('click',e=>{if(e.target.matches('[data-compare]'))return;state.selected=b.dataset.key;renderList();const p=state.cards.find(x=>x.citekey===state.selected);p.has_card?loadDetail(p.citekey):renderUnbuilt(p)}));
document.querySelectorAll('[data-compare]').forEach(b=>b.addEventListener('change',e=>{const k=e.target.dataset.compare;if(e.target.checked){if(state.compare.size>=12){e.target.checked=false;return toast('一次最多选择 12 篇')}state.compare.add(k)}else state.compare.delete(k);updateSelectionCounts()}));
updateSelectionCounts();if(state.libMode==='table')renderTable()}
function renderUnbuilt(p){$('readerPanel').innerHTML=`<div class="reader-head"><span class="citekey">${esc(p.citekey)}</span><h2>${esc(p.title)}</h2><div class="reader-head-meta"><span class="tag">未精读</span><a class="tag" href="zotero://select/library/items/${encodeURIComponent(p.zotero_item_key)}">在 Zotero 打开 ↗</a></div></div>${metaBlock(p)}<div class="reader-actions" style="margin-top:16px"><button class="button" id="prepareReading">生成精读</button></div><p class="muted" style="margin-top:12px">先选择 Zotero 附件，再生成带原文证据的精读草稿。采用后可以同步到论文下的 Zotero 子笔记。</p>`;$('evidenceContent').innerHTML='<p class="muted">采用草稿后，这里显示每条结论对应的原文。</p>';$('prepareReading').onclick=()=>materialDialog(p)}
async function materialDialog(p){try{const m=await api(`/api/papers/${encodeURIComponent(p.zotero_item_key)}/material`),items=m.attachments.filter(x=>x.indexed);const d=document.createElement('dialog');d.className='settings-dialog';d.innerHTML=`<form method="dialog"><div class="dialog-head"><div><span class="eyebrow">READING MATERIAL</span><h2>生成精读</h2></div><button class="close-button" value="cancel">×</button></div><p class="muted"><strong>${esc(m.title)}</strong><br>仅发送下方所选附件的索引全文；你的 Zotero 个人笔记不会发送。</p><div class="settings-section">${items.length?items.map((x,i)=>`<label class="attachment-choice"><input type="radio" name="attachment" value="${esc(x.key)}" ${i?'':'checked'}> ${esc(x.name)}<small>已建立全文索引</small></label>`).join(''):'<p class="muted">没有可用的全文索引，请先让 Zotero 完成 PDF 索引。</p>'}</div><div class="dialog-footer"><button class="button" id="startReading" ${items.length?'':'disabled'}>开始生成草稿</button><button class="button ghost" value="cancel">取消</button></div></form>`;document.body.append(d);d.addEventListener('close',()=>d.remove());d.showModal();d.querySelector('#startReading')?.addEventListener('click',async e=>{e.preventDefault();try{const a=d.querySelector('input[name="attachment"]:checked')?.value,task=await api('/api/reading-tasks',{method:'POST',body:JSON.stringify({item_key:p.zotero_item_key,attachment_key:a,collection:state.collection})});d.close();showTask(task.task_id);toast(`已读取 ${task.snapshot.chunk_count} 个全文片段`) }catch(err){toast(err.message)}})}catch(e){toast(e.message)}}
async function loadDetail(k){try{const d=await api(`/api/cards/${encodeURIComponent(k)}?collection=${encodeURIComponent(state.collection)}`);state.details.set(k,d);renderReader(d)}catch(e){toast(e.message)}}
function renderReader(d){const s=d.summary,hidden=['Bibliographic Information','My Thoughts'],parts=Object.entries(d.sections).filter(([n])=>!hidden.includes(n)&&!n.startsWith('#'));$('readerPanel').innerHTML=`<div class="reader-head"><span class="citekey">${esc(s.citekey)}</span><h2>${esc(s.title)}</h2><div class="reader-head-meta"><span class="tag">${esc(s.reading_type||'精读卡')}</span><span class="tag">${esc(s.evidence_status)}</span><span class="tag">${esc(s.sync_status||'未同步')}</span><a class="tag" href="zotero://select/library/items/${encodeURIComponent(s.zotero_item_key||'')}">打开论文 ↗</a></div><div class="reader-actions"><button class="button" id="syncCard">同步到 Zotero</button></div></div>${(()=>{const c=state.cards.find(x=>x.citekey===s.citekey);return c?metaBlock(c):''})()}${parts.map(([n,c])=>`<article class="reader-section"><h3>${esc(n)}</h3><div>${text(c)}</div></article>`).join('')}`;renderEvidence(d);$('syncCard').onclick=()=>syncCard(s)}
function renderEvidence(d){$('evidenceContent').innerHTML=d.evidence.length?d.evidence.map(x=>`<div class="evidence-card"><strong>【${esc(x.id)}】· ${esc(x.status)}</strong><details class="source-excerpt"><summary>查看原文与位置</summary><p class="source-note">${esc(x.source.message||'')}</p><blockquote>${esc(x.source.text||'')}</blockquote></details></div>`).join('')+'<div class="question-form"><span class="eyebrow">个人笔记</span><p class="muted">请在 Zotero 论文条目下新建独立笔记，记录你的想法。</p></div>':'<p class="muted">这张卡片没有可展示的原文证据。</p>'}
async function syncCard(s){try{const r=await api(`/api/cards/${encodeURIComponent(s.citekey)}/sync?collection=${encodeURIComponent(state.collection)}`,{method:'POST'});toast(r.status==='created'?'已创建 Zotero 精读卡子笔记':'Zotero 精读卡已同步');loadDetail(s.citekey)}catch(e){toast(e.message)}}
function showView(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===`${v}View`));document.querySelectorAll('.nav-tab').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='compare')compare();if(v==='map')map();if(v==='daily')loadDaily();if(v==='history')loadHistory()}
const SLOT_CLASS={relevance:'slot-relevance',theory:'slot-theory',method:'slot-method'};
function stars(n){return '⭐'.repeat(Math.max(1,Math.min(5,n||3)))}
function dailyReview(p){const r=p.ai_review;if(!r)return '';const rows=[['推荐评语',r.verdict],['研究亮点',r.highlights],['方法评价',r.method_review],['可借鉴之处',r.relevance],['阅读提醒',r.caution]].filter(([,v])=>v);const zh=r.abstract_zh?`<details class="meta-abstract" open><summary>中文摘要（AI 翻译，点击可收起）</summary><p>${text(r.abstract_zh)}</p></details>`:'';return `<div class="daily-review"><h3>✦ AI 分析与推荐评语</h3>${rows.length?`<dl>${rows.map(([k,v])=>`<div><dt>${k}</dt><dd>${text(v)}</dd></div>`).join('')}</dl>`:''}${zh}</div>`}
function dailyCard(p){const meta=p.venue_meta||{},fb=p.feedback||{},a=p.analysis;const badge=[esc(p.venue||'未知期刊'),meta.if_2025?`IF ${esc(meta.if_2025)}`:'',meta.rank?esc(meta.rank):''].filter(Boolean).join(' · ');const link=p.doi_url||p.publisher_url||p.openalex_url||'';const analysisHtml=a?`<details class="daily-analysis" open><summary>深度解读${a.inferred?'（基于标题与期刊推断，请以原文为准）':''}</summary><dl>${[['为什么值得读',a.why_read],['RQ / 理论',a.rq_theory],['数据与方法',a.data_method],['核心发现',a.findings],['最值得精读',a.focus_section],['可直接借鉴',a.takeaways]].filter(([,v])=>v).map(([k,v])=>`<div><dt>${k}</dt><dd>${text(v)}</dd></div>`).join('')}</dl></details>`:`<p class="muted">入选理由：${esc(p.slot_hits?.slice(0,5).join('、')||'综合评分靠前')}</p>`;return `<article class="daily-card ${fb.read?'is-read':''}"><header class="daily-card-head"><span class="slot-pill ${SLOT_CLASS[p.slot]||''}">${esc(p.slot_label)}</span><span class="daily-badge">${badge}</span>${p.backfilled_window?'<span class="daily-backfill">回溯推荐</span>':''}</header><h2>${link?`<a href="${esc(link)}" target="_blank" rel="noopener">${esc(p.title)}</a>`:esc(p.title)}</h2><p class="daily-meta">${esc((p.authors||[]).slice(0,6).join('; '))} · ${esc(p.publication_date||'')}</p><p class="daily-priority">精读优先级：${stars(a?.priority)}${p.doi?` · <a href="${esc(p.doi_url)}" target="_blank" rel="noopener">DOI</a>`:''}</p>${analysisHtml}${dailyReview(p)}${p.abstract?`<details class="daily-abstract"><summary>摘要原文</summary><p>${text(p.abstract)}</p></details>`:'<p class="muted">暂无公开摘要（已尝试三个来源）。</p>'}<footer class="daily-actions"><button class="chip ${fb.read?'on':''}" data-fb="read" data-val="${fb.read?'0':'1'}">${fb.read?'已读 ✓':'标为已读'}</button><button class="chip ${fb.starred?'on':''}" data-fb="starred" data-val="${fb.starred?'0':'1'}">${fb.starred?'已收藏 ★':'收藏'}</button><button class="chip ${fb.useful===true?'on':''}" data-fb="useful" data-val="${fb.useful===true?'null':'1'}">有用</button><button class="chip ${fb.useful===false?'on danger':''}" data-fb="useful" data-val="${fb.useful===false?'null':'0'}">无用</button><button class="chip ai-chip" data-analyze>${p.ai_review?'重新 AI 分析':'✦ AI 分析'}</button></footer></article>`}
function bindDailyActions(container,papers,reload){container.querySelectorAll('.daily-card').forEach((card,i)=>{const p=papers[i];card.querySelectorAll('[data-fb]').forEach(btn=>btn.onclick=async()=>{const raw=btn.dataset.val,value=raw==='null'?null:raw==='1';try{await api('/api/daily/feedback',{method:'POST',body:JSON.stringify({date:p.date,dedupe_key:p.dedupe_key,field:btn.dataset.fb,value})});reload()}catch(e){toast(e.message)}});const analyzeBtn=card.querySelector('[data-analyze]');if(analyzeBtn)analyzeBtn.onclick=async()=>{analyzeBtn.disabled=true;analyzeBtn.textContent='分析中…（约 30 秒）';try{await api('/api/daily/analyze',{method:'POST',body:JSON.stringify({date:p.date,dedupe_key:p.dedupe_key})});toast('AI 分析与摘要翻译已生成');reload()}catch(e){analyzeBtn.disabled=false;analyzeBtn.textContent='✦ AI 分析';toast(e.message)}}})}
async function loadDaily(){const box=$('dailyContent'),select=$('dailyDateSelect'),button=$('generateDaily');try{const day=select.value||undefined,d=await api(`/api/daily${day?`?date=${encodeURIComponent(day)}`:''}`),dates=[...new Set([d.date,...d.dates].filter(Boolean))];$('dailyDateText').textContent=dateLabel(d.date);select.innerHTML=dates.map(x=>`<option value="${esc(x)}" ${x===d.date?'selected':''}>${esc(dateLabel(x))}</option>`).join('');const today=new Date().toISOString().slice(0,10),todayGenerated=d.dates.includes(today);button.disabled=todayGenerated;button.textContent=todayGenerated?'今日推荐已生成':'获取今日精读推荐';if(!d.papers.length){box.innerHTML='<div class="empty-state"><span class="empty-glyph" aria-hidden="true">＋</span><h2>这一天还没有推荐</h2><p>点击“获取今日精读推荐”，系统会检索并保存三个槽位的论文；同一天重复点击不会重新计算。</p></div>';return}box.innerHTML=d.papers.map(dailyCard).join('');bindDailyActions(box,d.papers,loadDaily)}catch(e){box.innerHTML=`<p class="muted">${esc(e.message)}</p>`}}
async function waitForToday(button,fallbackMessage){const today=new Date().toISOString().slice(0,10);for(let attempt=0;attempt<30;attempt++){await new Promise(resolve=>setTimeout(resolve,6000));try{const d=await api(`/api/daily?date=${today}`);if(d.papers.length){$('dailyDateSelect').value=today;await loadDaily();toast('今日三篇推荐已保存');return}}catch{/* 服务仍在生成，继续等待 */}}button.disabled=false;button.textContent='重新获取今日推荐';toast(fallbackMessage)}
async function generateDaily(){const button=$('generateDaily');button.disabled=true;button.textContent='正在检索并生成…（约 1–3 分钟）';try{const d=await api('/api/daily/generate',{method:'POST'});if(d.generating){await waitForToday(button,'生成时间较长，请稍后手动刷新页面查看。');return}$('dailyDateSelect').value=d.date;await loadDaily();toast(d.generated?'今日三篇推荐已保存':'今日推荐已存在，已直接载入')}catch(e){button.textContent='生成中，正在等待结果…';await waitForToday(button,e.message)}}
async function loadHistory(){const box=$('historyContent'),dateSelect=$('historyDateSelect');try{const params=new URLSearchParams();if($('historySlotFilter').value)params.set('slot',$('historySlotFilter').value);if($('historyReadFilter').value)params.set('read_state',$('historyReadFilter').value);if($('historyVenueInput').value)params.set('venue',$('historyVenueInput').value);const d=await api(`/api/daily/history?${params}`),selected=dateSelect.value;dateSelect.innerHTML='<option value="">全部日期</option>'+d.dates.map(x=>`<option value="${esc(x)}" ${x===selected?'selected':''}>${esc(dateLabel(x))}</option>`).join('');const papers=selected?d.papers.filter(p=>p.date===selected):d.papers;if(!papers.length){box.innerHTML='<div class="empty-state"><h2>没有符合条件的历史推荐</h2><p>生成今日推荐后，它会按日期保存在这里。</p></div>';return}let last='';box.innerHTML=papers.map(p=>{const heading=p.date!==last?`<div class="history-date">${esc(dateLabel(p.date))}</div>`:'';last=p.date;return heading+dailyCard(p)}).join('');bindDailyActions(box,papers,loadHistory)}catch(e){box.innerHTML=`<p class="muted">${esc(e.message)}</p>`}}
async function compare(){const box=$('compareContent'),keys=selectedCards().filter(p=>p.has_card).map(p=>p.citekey);if(keys.length<2){box.className='compare-empty';box.innerHTML=`<span class="empty-glyph">＋</span><h2>从精读桌勾选 2–4 篇已有精读卡的论文</h2><p>当前已勾选 ${keys.length} 篇有精读卡的论文。</p>`;return}try{const d=await api('/api/compare',{method:'POST',body:JSON.stringify({collection:state.collection,citekeys:keys.slice(0,4)})});state.compareData=d;if(!state.compareDim)state.compareDim='全部维度';renderCompare()}catch(e){toast(e.message)}}
function renderCompare(){const d=state.compareData,box=$('compareContent');if(!d)return;box.className='compare-board';
const cols=`style="grid-template-columns:repeat(${d.cards.length},minmax(230px,1fr))"`;
const metaFor=c=>{const p=state.cards.find(x=>x.citekey===c.citekey),m=p?.paper_meta||{},v=m.venue_meta||{};return [[yearOf(m),m.journal].filter(Boolean).join(' · '),v.if_2025?`IF ${v.if_2025}${v.rank?` · ${v.rank}`:''}`:''].filter(Boolean).join('　')||c.citekey};
const dims=['全部维度',...d.rows.map(r=>r.label)];
const rows=state.compareDim==='全部维度'?d.rows:d.rows.filter(r=>r.label===state.compareDim);
box.innerHTML=`<div class="compare-tabs">${dims.map(x=>`<button class="chip ${x===state.compareDim?'on':''}" data-dim="${esc(x)}">${esc(x)}</button>`).join('')}</div><div class="compare-heads" ${cols}>${d.cards.map((c,i)=>`<div class="compare-head-card"><span class="compare-index">${'ABCD'[i]}</span><strong>${esc(c.title)}</strong><small>${esc(metaFor(c))}</small></div>`).join('')}</div>${rows.map(r=>`<section class="compare-dim"><h3>${esc(r.label)}</h3><div class="compare-cells" ${cols}>${r.values.map((v,i)=>`<div class="compare-cell"><span class="compare-index">${'ABCD'[i]}</span><div>${text(v)}</div></div>`).join('')}</div></section>`).join('')}`;
box.querySelectorAll('[data-dim]').forEach(b=>b.onclick=()=>{state.compareDim=b.dataset.dim;renderCompare()})}
async function runCompareAI(){const keys=selectedCards().filter(p=>p.has_card).map(p=>p.citekey).slice(0,4);if(keys.length<2)return toast('请先在精读桌勾选 2–4 篇已有精读卡的论文');try{await api('/api/ai',{method:'POST',body:JSON.stringify({type:'compare',citekeys:keys,collection:state.collection})});openTasks();toast('AI 比较任务已开始，可在任务中心查看进度')}catch(e){toast(e.message)}}
function jumpToCard(citekey){showView('library');state.selected=citekey;renderList();const p=state.cards.find(x=>x.citekey===citekey);if(p)p.has_card?loadDetail(citekey):renderUnbuilt(p);setTimeout(()=>document.querySelector(`.paper-item[data-key="${CSS.escape(citekey)}"]`)?.scrollIntoView({block:'center',behavior:'smooth'}),100)}
function mapFocus(theory,method){const d=state.mapData;if(!d)return;const keys=[...new Set(d.links.filter(x=>(!theory||x.theory===theory)&&(!method||x.method===method)).map(x=>x.citekey))];const label=[theory,method].filter(Boolean).join(' × ')||'全部';
$('mapDetail').innerHTML=keys.length?`<p class="map-focus-label">${esc(label)} · ${keys.length} 篇</p>${keys.map(k=>`<button class="map-paper" data-jump="${esc(k)}"><strong>${esc(d.titles?.[k]||k)}</strong><small>${esc(k)} · 打开精读卡 →</small></button>`).join('')}`:`<p class="muted">「${esc(label)}」暂无对应论文。</p>`;
$('mapDetail').querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>jumpToCard(b.dataset.jump));
document.querySelectorAll('.mx-cell,.mx-head,.method-chip').forEach(el=>el.classList.toggle('focus',(el.dataset.theory||'')===(theory||'')&&(el.dataset.method||'')===(method||'')))}
async function map(){try{const d=await api(`/api/map?collection=${encodeURIComponent(state.collection)}`);state.mapData=d;$('mapCount').textContent=d.card_count;
const cellCount=(t,m)=>d.links.filter(x=>x.theory===t&&x.method===m).length;
$('matrix').innerHTML=d.theories.length&&d.methods.length?`<table class="matrix"><thead><tr><th>理论 ＼ 方法</th>${d.methods.map(x=>`<th><button class="mx-head" data-method="${esc(x.name)}">${esc(x.name)}</button></th>`).join('')}</tr></thead><tbody>${d.theories.map(t=>`<tr><th><button class="mx-head" data-theory="${esc(t.name)}">${esc(t.name)} <b>${t.count}</b></button></th>${d.methods.map(m=>{const n=cellCount(t.name,m.name);return n?`<td><button class="mx-cell" data-theory="${esc(t.name)}" data-method="${esc(m.name)}">${n}</button></td>`:'<td class="mx-empty">·</td>'}).join('')}</tr>`).join('')}</tbody></table>`:'<p class="muted">采用更多结构化精读卡后，这里会生成理论与方法关系。</p>';
$('incompleteList').innerHTML=d.incomplete.length?d.incomplete.map(k=>`<button class="map-paper subtle" data-jump="${esc(k)}"><strong>${esc(d.titles?.[k]||k)}</strong><small>缺少理论或方法标注 · 打开卡片补全 →</small></button>`).join(''):'<p class="muted">所有精读卡都有理论与方法标注。</p>';
$('incompleteList').querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>jumpToCard(b.dataset.jump));
$('methodList').innerHTML=d.methods.map(x=>`<button class="method-chip" data-method="${esc(x.name)}">${esc(x.name)} <b>${x.count}</b></button>`).join('');
$('matrix').querySelectorAll('.mx-cell,.mx-head').forEach(el=>el.onclick=()=>mapFocus(el.dataset.theory||'',el.dataset.method||''));
$('methodList').querySelectorAll('.method-chip').forEach(el=>el.onclick=()=>mapFocus('',el.dataset.method))}catch(e){toast(e.message)}}
const TASK_TYPE={read:'精读生成',enrich:'AI 标签·翻译',compare:'AI 比较'};
const ACTIVE_STATUS=['排队','分析中'];
function fmtDur(s){if(s==null||!isFinite(s))return '';return s<60?`${Math.max(1,Math.round(s))} 秒`:`${Math.floor(s/60)} 分 ${String(Math.round(s%60)).padStart(2,'0')} 秒`}
function taskTime(t){if(t.duration_seconds!=null)return `用时 ${fmtDur(t.duration_seconds)}`;const start=Date.parse(t.started_at||t.created_at);if(!start)return '';return ACTIVE_STATUS.includes(t.status)?`已运行 ${fmtDur((Date.now()-start)/1000)}`:''}
function statusClass(t){return {'排队':'queued','分析中':'running','待采用':'done','完成':'done','已采用':'done','部分完成':'warn','失败':'error','已中断':'error'}[t.status]||'queued'}
function showTask(){openTasks()}
function openTasks(){$('taskDrawer').classList.add('open');refreshTasks()}
function closeTasks(){$('taskDrawer').classList.remove('open')}
async function refreshTasks(){clearTimeout(window.taskTimer);try{const d=await api('/api/tasks');state.tasks=d.tasks;const nowActive=new Set(d.tasks.filter(t=>ACTIVE_STATUS.includes(t.status)).map(t=>t.id));
if(state.activeTasks)for(const t of d.tasks){if(state.activeTasks.has(t.id)&&!nowActive.has(t.id)){if(t.type==='enrich'){loadCards();toast('AI 标签与翻译已完成')}if(t.type==='read'&&t.status==='待采用')toast('精读草稿已生成，请在任务中心查看并采用')}}
state.activeTasks=nowActive;const badge=$('taskBadge');badge.hidden=!nowActive.size;badge.textContent=nowActive.size;renderTasks();
if(nowActive.size||$('taskDrawer').classList.contains('open')&&d.tasks.length)window.taskTimer=setTimeout(refreshTasks,nowActive.size?1500:6000)}catch(e){if($('taskDrawer').classList.contains('open'))$('taskBody').innerHTML=`<p class="muted">${esc(e.message)}</p>`}}
function renderTasks(){if(!$('taskDrawer').classList.contains('open'))return;const tasks=state.tasks||[];if(!tasks.length){$('taskBody').innerHTML='<p class="muted">还没有 AI 任务。生成精读、AI 标签或 AI 比较后会显示在这里，并实时展示状态与运行时间。</p>';return}
$('taskBody').innerHTML=tasks.map(t=>{const prog=t.progress?`<div class="task-progress"><span style="width:${t.progress.total?Math.round(t.progress.done/t.progress.total*100):0}%"></span></div><p class="muted task-progress-text">${t.progress.done}/${t.progress.total}${t.progress.current&&ACTIVE_STATUS.includes(t.status)?` · 正在处理：${esc(t.progress.current)}`:''}</p>`:'';
const fails=(t.items||[]).filter(x=>!x.ok);
const failList=fails.length?`<details class="task-fails"><summary>${fails.length} 篇失败</summary>${fails.map(x=>`<p class="muted">${esc(x.title)}：${esc(x.error||'')}</p>`).join('')}</details>`:'';
const result=t.result?`<details class="task-result-box"><summary>查看${t.type==='read'?'精读草稿':'结果'}</summary><div class="task-result">${text(t.result)}</div></details>`:'';
const adopt=t.type==='read'&&t.status==='待采用'?`<button class="button task-adopt" data-adopt="${esc(t.id)}">采用为正式精读卡</button>`:'';
const snap=t.snapshot?`<p class="muted task-snap">${t.snapshot.chunk_count} 个全文片段 · 调用 ${t.call_count||0} 次</p>`:'';
return `<article class="task-item"><header><span class="task-status ${statusClass(t)}">${esc(t.status)}</span><span class="task-time">${esc(taskTime(t))}</span></header><strong>${esc(t.label||TASK_TYPE[t.type]||'AI 任务')}</strong>${snap}${prog}${failList}${t.error?`<p class="task-error">${esc(t.error)}</p>`:''}${result}${adopt}</article>`}).join('');
$('taskBody').querySelectorAll('[data-adopt]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const d=await api(`/api/tasks/${b.dataset.adopt}/adopt`,{method:'POST'});state.selected=d.summary.citekey;await loadCards();refreshTasks();toast('精读卡已采用，可以同步到 Zotero')}catch(e){b.disabled=false;toast(e.message)}})}
async function enrichSelectedPapers(){const sel=selectedCards();if(!sel.length)return toast('请先在左侧勾选论文');try{const r=await api('/api/papers/enrich',{method:'POST',body:JSON.stringify({collection:state.collection,item_keys:sel.map(p=>p.zotero_item_key).filter(Boolean)})});openTasks();toast(`已开始为 ${r.count} 篇论文生成标签与翻译`)}catch(e){toast(e.message)}}
async function batchRead(){const sel=selectedCards().filter(p=>!p.has_card);if(!sel.length)return toast('请勾选还没有精读卡的论文');if(sel.length>6)return toast('批量精读一次最多 6 篇');toast('正在读取全文并排队，可能需要一两分钟…');try{const r=await api('/api/reading-tasks/batch',{method:'POST',body:JSON.stringify({collection:state.collection,item_keys:sel.map(p=>p.zotero_item_key).filter(Boolean)})});openTasks();toast(r.errors.length?`${r.created.length} 篇已排队，${r.errors.length} 篇无法生成：${r.errors[0].error||''}`:`${r.created.length} 篇精读任务已排队`)}catch(e){toast(e.message)}}
function toggleSelectAll(){const sel=selectedCards();if(sel.length&&sel.length===state.cards.length)state.compare.clear();else state.compare=new Set(state.cards.slice(0,12).map(p=>p.citekey));renderList()}
function renderTable(){if(!state.cards.length){$('libraryTable').innerHTML='<p class="muted">当前筛选没有论文。</p>';return}
$('libraryTable').innerHTML=`<table class="library-table"><thead><tr><th class="lt-check"><span class="sr-only">选择</span></th><th>标题</th><th>作者</th><th>年份</th><th>期刊</th><th>IF · 分区</th><th>标签</th><th>状态</th></tr></thead><tbody>${state.cards.map(p=>{const m=p.paper_meta||{},v=m.venue_meta||{},en=p.enrichment||{};
return `<tr class="${p.citekey===state.selected?'active':''}" data-key="${esc(p.citekey)}"><td class="lt-check"><input type="checkbox" data-tcompare="${esc(p.citekey)}" aria-label="选择论文：${esc(p.title)}" ${state.compare.has(p.citekey)?'checked':''}></td><td class="lt-title"><strong>${esc(p.title)}</strong>${en.quick_take?`<small>${esc(en.quick_take)}</small>`:''}</td><td>${esc(authorsLine(m))||'—'}</td><td>${esc(yearOf(m))||'—'}</td><td class="lt-journal">${esc(m.journal||'—')}</td><td>${v.if_2025?`${esc(v.if_2025)}${v.rank?` · ${esc(v.rank)}`:''}`:'—'}</td><td class="lt-tags">${tagChips(p,4)||'—'}</td><td><span class="status-pill">${p.has_card?'已有精读卡':'未精读'}</span></td></tr>`}).join('')}</tbody></table>`;
$('libraryTable').querySelectorAll('tr[data-key]').forEach(row=>row.onclick=e=>{if(e.target.matches('[data-tcompare]'))return;setLibMode('rail');jumpToCard(row.dataset.key)});
$('libraryTable').querySelectorAll('[data-tcompare]').forEach(b=>b.onchange=e=>{const k=e.target.dataset.tcompare;if(e.target.checked){if(state.compare.size>=12){e.target.checked=false;return toast('一次最多选择 12 篇')}state.compare.add(k)}else state.compare.delete(k);updateSelectionCounts();renderList()})}
function setLibMode(mode){state.libMode=mode;$('modeRail').classList.toggle('on',mode==='rail');$('modeTable').classList.toggle('on',mode==='table');document.querySelector('.desk-grid').style.display=mode==='rail'?'':'none';$('libraryTable').hidden=mode!=='table';if(mode==='table')renderTable()}
async function loadSettings(){try{const s=await api('/api/settings'),ai=s.ai;state.aiLocked=!!(ai.managed||ai.published);const box=$('aiManagedStatus');
if(ai.managed){box.hidden=false;$('aiManagedDot').classList.add('green');$('aiManagedLabel').textContent=`DeepSeek 已由服务端配置 · 模型 ${ai.model}`;$('aiEditableFields').hidden=true;$('aiConfigHint').textContent='API Key 保存在 Vercel 环境变量中，网页不需要也无法查看；如需更换请在 Vercel 修改 DEEPSEEK_API_KEY 后重新部署。';$('saveSettings').hidden=true;$('aiTestStatus').textContent='已配置，可直接使用'}
else if(ai.published){box.hidden=false;$('aiManagedDot').classList.remove('green');$('aiManagedLabel').textContent='DeepSeek 尚未配置';$('aiEditableFields').hidden=true;$('aiConfigHint').textContent='请在 Vercel 项目的 Environment Variables 添加 DEEPSEEK_API_KEY（可选 DEEPSEEK_MODEL、DEEPSEEK_BASE_URL），保存后重新部署即可长期生效。';$('saveSettings').hidden=true;$('aiTestStatus').textContent='未配置'}
else{$('aiBaseUrl').value=ai.base_url;$('aiModel').value=ai.model;if(ai.configured)$('aiTestStatus').textContent='已配置'}
const z=s.zotero;
if(z.mode==='web')connection(!!z.connected,z.connected?`Zotero Cloud 已连接 · ${z.collection_count} 个集合${z.writable?' · 可同步笔记':'（只读：请在 zotero.org/settings/keys 勾选 Allow write access）'}`:`Zotero Cloud 未连接：${z.error||'请检查 ZOTERO_USER_ID / ZOTERO_API_KEY'}`);
else connection(!z.error,z.error?'Zotero 未连接':`Zotero Desktop ${z.version||''} 已连接${z.writable?'，可同步笔记（Web API）':'；'+(z.web_api?.hint||'配置 Zotero Web API 后可同步笔记')}`)}catch(e){}}
async function saveSettings(){if(state.aiLocked)return toast('AI 已由服务端配置，无需在网页保存。');try{const r=await api('/api/settings/ai',{method:'PATCH',body:JSON.stringify({base_url:$('aiBaseUrl').value,model:$('aiModel').value,api_key:$('aiKey').value})});$('aiBaseUrl').value=r.base_url;$('aiTestStatus').textContent=r.configured?'已配置':'尚未配置';toast(r.notice||'AI 设置已保存')}catch(e){toast(e.message)}}
document.querySelectorAll('.nav-tab').forEach(x=>x.onclick=()=>showView(x.dataset.view));$('collectionSelect').onchange=async e=>{state.collection=e.target.value;localStorage.setItem('researchCollection',state.collection);state.selected=null;state.compare.clear();await loadCards()};$('searchInput').oninput=()=>{clearTimeout(window.timer);window.timer=setTimeout(loadCards,250)};$('statusFilter').onchange=loadCards;$('refreshButton').onclick=loadCards;$('modeRail').onclick=()=>setLibMode('rail');$('modeTable').onclick=()=>setLibMode('table');$('selectAllPapers').onclick=toggleSelectAll;$('enrichSelected').onclick=enrichSelectedPapers;$('batchReadSelected').onclick=batchRead;$('compareSelected').onclick=()=>showView('compare');$('runCompareAI').onclick=runCompareAI;$('openTasksButton').onclick=openTasks;$('openSettings').onclick=()=>$('settingsDialog').showModal();$('openSettingsSmall').onclick=()=>$('settingsDialog').showModal();$('saveSettings').onclick=saveSettings;$('testAI').onclick=async()=>{if(!state.aiLocked)await saveSettings();try{$('aiTestStatus').textContent=(await api('/api/settings/ai/test',{method:'POST'})).message}catch(e){toast(e.message)}};document.addEventListener('click',e=>{if(e.target.closest('#closeTask'))closeTasks()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('taskDrawer').classList.contains('open'))closeTasks()});$('generateDaily').onclick=generateDaily;$('dailyDateSelect').onchange=loadDaily;$('historyDateSelect').onchange=loadHistory;$('historySlotFilter').onchange=loadHistory;$('historyReadFilter').onchange=loadHistory;$('historyVenueInput').oninput=()=>{clearTimeout(window.historyTimer);window.historyTimer=setTimeout(loadHistory,300)};boot();
