const state={token:'',collection:'',cards:[],selected:null,compare:new Set(),details:new Map(),task:null,aiLocked:false};
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const text=value=>esc(value).replace(/\n/g,'<br>');
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json','X-Research-Session':state.token,...(options.headers||{})}}),data=await r.json();if(!r.ok)throw new Error(data.error||`请求失败（${r.status}）`);return data}
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3000)}
function dateLabel(value){if(!value)return '尚未生成';const [year,month,day]=value.split('-').map(Number);return `${year} 年 ${month} 月 ${day} 日`}
function connection(ok,label){$('zoteroDot').classList.toggle('ok',ok);$('connectionText').textContent=label;$('zoteroStatusDot').classList.toggle('green',ok);$('zoteroStatusLabel').textContent=label}
async function boot(){try{state.token=(await fetch('/api/session').then(r=>r.json())).token;loadDaily();const data=await api('/api/collections'),last=localStorage.getItem('researchCollection');state.collection=data.collections.includes(last)?last:(data.collections.includes('framing')?'framing':data.collections[0]||'');$('collectionSelect').innerHTML=data.collections.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');$('collectionSelect').value=state.collection;await loadCards();connection(true,'Zotero 与本地卡片已连接')}catch(e){connection(false,'本地资料读取失败');toast(e.message)}loadSettings()}
async function loadCards(){const d=await api(`/api/cards?${new URLSearchParams({collection:state.collection,q:$('searchInput').value,status:$('statusFilter').value})}`);state.cards=d.cards;const built=d.cards.filter(x=>x.has_card);$('cardCount').textContent=built.length;$('railCount').textContent=`${built.length} 张精读 · ${d.cards.length-built.length} 待处理`;$('questionCount').textContent='0';renderList();if(!state.selected||!d.cards.some(x=>x.citekey===state.selected))state.selected=d.cards[0]?.citekey||null;if(state.selected){const p=d.cards.find(x=>x.citekey===state.selected);p.has_card?loadDetail(p.citekey):renderUnbuilt(p)}}
function renderList(){if(!state.cards.length){$('paperList').innerHTML='<p class="muted">当前筛选没有论文。</p>';return}$('paperList').innerHTML=state.cards.map(p=>`<button class="paper-item ${p.citekey===state.selected?'active':''}" data-key="${esc(p.citekey)}"><input class="paper-check" type="checkbox" data-compare="${esc(p.citekey)}" aria-label="加入比较：${esc(p.title)}" ${p.has_card?'':'disabled'} ${state.compare.has(p.citekey)?'checked':''}><strong>${esc(p.title)}</strong><small>${esc(p.citekey)}</small><span class="status-pill">${p.has_card?'已有精读卡':'未精读'}</span></button>`).join('');document.querySelectorAll('.paper-item').forEach(b=>b.addEventListener('click',e=>{if(e.target.matches('[data-compare]'))return;state.selected=b.dataset.key;renderList();const p=state.cards.find(x=>x.citekey===state.selected);p.has_card?loadDetail(p.citekey):renderUnbuilt(p)}));document.querySelectorAll('[data-compare]').forEach(b=>b.addEventListener('change',e=>{const k=e.target.dataset.compare;if(e.target.checked){if(state.compare.size>=4){e.target.checked=false;return toast('一次最多比较 4 篇')}state.compare.add(k)}else state.compare.delete(k);$('compareCount').textContent=state.compare.size}));$('compareCount').textContent=state.compare.size}
function renderUnbuilt(p){$('readerPanel').innerHTML=`<div class="empty-state"><span class="empty-glyph">⌁</span><h2>从全文开始生成精读</h2><p>先选择 Zotero 附件，再生成带原文证据的精读草稿。采用后可以同步到论文下的 Zotero 子笔记。</p><div class="reader-actions" style="justify-content:center"><button class="button" id="prepareReading">生成精读</button><a class="button subtle" href="zotero://select/library/items/${encodeURIComponent(p.zotero_item_key)}">在 Zotero 打开论文</a></div></div>`;$('evidenceContent').innerHTML='<p class="muted">采用草稿后，这里显示每条结论对应的原文。</p>';$('prepareReading').onclick=()=>materialDialog(p)}
async function materialDialog(p){try{const m=await api(`/api/papers/${encodeURIComponent(p.zotero_item_key)}/material`),items=m.attachments.filter(x=>x.indexed);const d=document.createElement('dialog');d.className='settings-dialog';d.innerHTML=`<form method="dialog"><div class="dialog-head"><div><span class="eyebrow">READING MATERIAL</span><h2>生成精读</h2></div><button class="close-button" value="cancel">×</button></div><p class="muted"><strong>${esc(m.title)}</strong><br>仅发送下方所选附件的索引全文；你的 Zotero 个人笔记不会发送。</p><div class="settings-section">${items.length?items.map((x,i)=>`<label class="attachment-choice"><input type="radio" name="attachment" value="${esc(x.key)}" ${i?'':'checked'}> ${esc(x.name)}<small>已建立全文索引</small></label>`).join(''):'<p class="muted">没有可用的全文索引，请先让 Zotero 完成 PDF 索引。</p>'}</div><div class="dialog-footer"><button class="button" id="startReading" ${items.length?'':'disabled'}>开始生成草稿</button><button class="button ghost" value="cancel">取消</button></div></form>`;document.body.append(d);d.addEventListener('close',()=>d.remove());d.showModal();d.querySelector('#startReading')?.addEventListener('click',async e=>{e.preventDefault();try{const a=d.querySelector('input[name="attachment"]:checked')?.value,task=await api('/api/reading-tasks',{method:'POST',body:JSON.stringify({item_key:p.zotero_item_key,attachment_key:a,collection:state.collection})});d.close();showTask(task.task_id);toast(`已读取 ${task.snapshot.chunk_count} 个全文片段`) }catch(err){toast(err.message)}})}catch(e){toast(e.message)}}
async function loadDetail(k){try{const d=await api(`/api/cards/${encodeURIComponent(k)}?collection=${encodeURIComponent(state.collection)}`);state.details.set(k,d);renderReader(d)}catch(e){toast(e.message)}}
function renderReader(d){const s=d.summary,hidden=['Bibliographic Information','My Thoughts'],parts=Object.entries(d.sections).filter(([n])=>!hidden.includes(n)&&!n.startsWith('#'));$('readerPanel').innerHTML=`<div class="reader-head"><span class="citekey">${esc(s.citekey)}</span><h2>${esc(s.title)}</h2><div class="reader-head-meta"><span class="tag">${esc(s.reading_type||'精读卡')}</span><span class="tag">${esc(s.evidence_status)}</span><span class="tag">${esc(s.sync_status||'未同步')}</span><a class="tag" href="zotero://select/library/items/${encodeURIComponent(s.zotero_item_key||'')}">打开论文 ↗</a></div><div class="reader-actions"><button class="button" id="syncCard">同步到 Zotero</button></div></div>${parts.map(([n,c])=>`<article class="reader-section"><h3>${esc(n)}</h3><div>${text(c)}</div></article>`).join('')}`;renderEvidence(d);$('syncCard').onclick=()=>syncCard(s)}
function renderEvidence(d){$('evidenceContent').innerHTML=d.evidence.length?d.evidence.map(x=>`<div class="evidence-card"><strong>【${esc(x.id)}】· ${esc(x.status)}</strong><details class="source-excerpt"><summary>查看原文与位置</summary><p class="source-note">${esc(x.source.message||'')}</p><blockquote>${esc(x.source.text||'')}</blockquote></details></div>`).join('')+'<div class="question-form"><span class="eyebrow">个人笔记</span><p class="muted">请在 Zotero 论文条目下新建独立笔记，记录你的想法。</p></div>':'<p class="muted">这张卡片没有可展示的原文证据。</p>'}
async function syncCard(s){try{const r=await api(`/api/cards/${encodeURIComponent(s.citekey)}/sync?collection=${encodeURIComponent(state.collection)}`,{method:'POST'});toast(r.status==='created'?'已创建 Zotero 精读卡子笔记':'Zotero 精读卡已同步');loadDetail(s.citekey)}catch(e){toast(e.message)}}
function showView(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===`${v}View`));document.querySelectorAll('.nav-tab').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='compare')compare();if(v==='map')map();if(v==='daily')loadDaily();if(v==='history')loadHistory()}
const SLOT_CLASS={relevance:'slot-relevance',theory:'slot-theory',method:'slot-method'};
function stars(n){return '⭐'.repeat(Math.max(1,Math.min(5,n||3)))}
function dailyCard(p){const meta=p.venue_meta||{},fb=p.feedback||{},a=p.analysis;const badge=[esc(p.venue||'未知期刊'),meta.if_2025?`IF ${esc(meta.if_2025)}`:'',meta.rank?esc(meta.rank):''].filter(Boolean).join(' · ');const link=p.doi_url||p.publisher_url||p.openalex_url||'';const analysisHtml=a?`<details class="daily-analysis" open><summary>深度解读${a.inferred?'（基于标题与期刊推断，请以原文为准）':''}</summary><dl>${[['为什么值得读',a.why_read],['RQ / 理论',a.rq_theory],['数据与方法',a.data_method],['核心发现',a.findings],['最值得精读',a.focus_section],['可直接借鉴',a.takeaways]].filter(([,v])=>v).map(([k,v])=>`<div><dt>${k}</dt><dd>${text(v)}</dd></div>`).join('')}</dl></details>`:`<p class="muted">入选理由：${esc(p.slot_hits?.slice(0,5).join('、')||'综合评分靠前')}</p>`;return `<article class="daily-card ${fb.read?'is-read':''}"><header class="daily-card-head"><span class="slot-pill ${SLOT_CLASS[p.slot]||''}">${esc(p.slot_label)}</span><span class="daily-badge">${badge}</span>${p.backfilled_window?'<span class="daily-backfill">回溯推荐</span>':''}</header><h2>${link?`<a href="${esc(link)}" target="_blank" rel="noopener">${esc(p.title)}</a>`:esc(p.title)}</h2><p class="daily-meta">${esc((p.authors||[]).slice(0,6).join('; '))} · ${esc(p.publication_date||'')}</p><p class="daily-priority">精读优先级：${stars(a?.priority)}${p.doi?` · <a href="${esc(p.doi_url)}" target="_blank" rel="noopener">DOI</a>`:''}</p>${analysisHtml}${p.abstract?`<details class="daily-abstract"><summary>摘要</summary><p>${text(p.abstract.length>900?p.abstract.slice(0,900)+'…':p.abstract)}</p></details>`:'<p class="muted">暂无公开摘要（已尝试三个来源）。</p>'}<footer class="daily-actions"><button class="chip ${fb.read?'on':''}" data-fb="read" data-val="${fb.read?'0':'1'}">${fb.read?'已读 ✓':'标为已读'}</button><button class="chip ${fb.starred?'on':''}" data-fb="starred" data-val="${fb.starred?'0':'1'}">${fb.starred?'已收藏 ★':'收藏'}</button><button class="chip ${fb.useful===true?'on':''}" data-fb="useful" data-val="${fb.useful===true?'null':'1'}">有用</button><button class="chip ${fb.useful===false?'on danger':''}" data-fb="useful" data-val="${fb.useful===false?'null':'0'}">无用</button></footer></article>`}
function bindDailyActions(container,papers,reload){container.querySelectorAll('.daily-card').forEach((card,i)=>{const p=papers[i];card.querySelectorAll('[data-fb]').forEach(btn=>btn.onclick=async()=>{const raw=btn.dataset.val,value=raw==='null'?null:raw==='1';try{await api('/api/daily/feedback',{method:'POST',body:JSON.stringify({date:p.date,dedupe_key:p.dedupe_key,field:btn.dataset.fb,value})});reload()}catch(e){toast(e.message)}})})}
async function loadDaily(){const box=$('dailyContent'),select=$('dailyDateSelect'),button=$('generateDaily');try{const day=select.value||undefined,d=await api(`/api/daily${day?`?date=${encodeURIComponent(day)}`:''}`),dates=[...new Set([d.date,...d.dates].filter(Boolean))];$('dailyDateText').textContent=dateLabel(d.date);select.innerHTML=dates.map(x=>`<option value="${esc(x)}" ${x===d.date?'selected':''}>${esc(dateLabel(x))}</option>`).join('');const today=new Date().toISOString().slice(0,10),todayGenerated=d.dates.includes(today);button.disabled=todayGenerated;button.textContent=todayGenerated?'今日推荐已生成':'获取今日精读推荐';if(!d.papers.length){box.innerHTML='<div class="empty-state"><span class="empty-glyph" aria-hidden="true">＋</span><h2>这一天还没有推荐</h2><p>点击“获取今日精读推荐”，系统会检索并保存三个槽位的论文；同一天重复点击不会重新计算。</p></div>';return}box.innerHTML=d.papers.map(dailyCard).join('');bindDailyActions(box,d.papers,loadDaily)}catch(e){box.innerHTML=`<p class="muted">${esc(e.message)}</p>`}}
async function generateDaily(){const button=$('generateDaily');button.disabled=true;button.textContent='正在检索并生成…';try{const d=await api('/api/daily/generate',{method:'POST'});$('dailyDateSelect').value=d.date;await loadDaily();toast(d.generated?'今日三篇推荐已保存':'今日推荐已存在，已直接载入')}catch(e){button.disabled=false;button.textContent='重新获取今日推荐';toast(e.message)}}
async function loadHistory(){const box=$('historyContent'),dateSelect=$('historyDateSelect');try{const params=new URLSearchParams();if($('historySlotFilter').value)params.set('slot',$('historySlotFilter').value);if($('historyReadFilter').value)params.set('read_state',$('historyReadFilter').value);if($('historyVenueInput').value)params.set('venue',$('historyVenueInput').value);const d=await api(`/api/daily/history?${params}`),selected=dateSelect.value;dateSelect.innerHTML='<option value="">全部日期</option>'+d.dates.map(x=>`<option value="${esc(x)}" ${x===selected?'selected':''}>${esc(dateLabel(x))}</option>`).join('');const papers=selected?d.papers.filter(p=>p.date===selected):d.papers;if(!papers.length){box.innerHTML='<div class="empty-state"><h2>没有符合条件的历史推荐</h2><p>生成今日推荐后，它会按日期保存在这里。</p></div>';return}let last='';box.innerHTML=papers.map(p=>{const heading=p.date!==last?`<div class="history-date">${esc(dateLabel(p.date))}</div>`:'';last=p.date;return heading+dailyCard(p)}).join('');bindDailyActions(box,papers,loadHistory)}catch(e){box.innerHTML=`<p class="muted">${esc(e.message)}</p>`}}
async function compare(){if(state.compare.size<2){$('compareContent').className='compare-empty';$('compareContent').innerHTML='<h2>选择 2–4 张已采用精读卡</h2>';return}try{const d=await api('/api/compare',{method:'POST',body:JSON.stringify({collection:state.collection,citekeys:[...state.compare]})});$('compareContent').className='compare-table-wrap';$('compareContent').innerHTML=`<table class="compare-table"><thead><tr><th>维度</th>${d.cards.map(x=>`<th>${esc(x.title)}</th>`).join('')}</tr></thead><tbody>${d.rows.map(x=>`<tr><th>${esc(x.label)}</th>${x.values.map(y=>`<td>${text(y)}</td>`).join('')}</tr>`).join('')}</tbody></table>`}catch(e){toast(e.message)}}
async function map(){try{const d=await api(`/api/map?collection=${encodeURIComponent(state.collection)}`);$('mapCount').textContent=d.card_count;$('matrix').innerHTML=d.theories.length&&d.methods.length?`<table class="matrix"><thead><tr><th>理论 ＼ 方法</th>${d.methods.map(x=>`<th>${esc(x.name)}</th>`).join('')}</tr></thead><tbody>${d.theories.map(t=>`<tr><th>${esc(t.name)}</th>${d.methods.map(m=>`<td>${d.links.filter(x=>x.theory===t.name&&x.method===m.name).length||'·'}</td>`).join('')}</tr>`).join('')}</tbody></table>`:'<p class="muted">采用更多结构化精读卡后，这里会生成理论与方法关系。</p>';$('incompleteList').innerHTML='';$('methodList').innerHTML=d.methods.map(x=>`<span class="method-chip">${esc(x.name)} <b>${x.count}</b></span>`).join('')}catch(e){toast(e.message)}}
function showTask(id){state.task=id;$('taskDrawer').classList.add('open');poll(id)}
async function poll(id){try{const t=await api(`/api/tasks/${id}`),meta=t.snapshot?`<p class="muted">已处理 ${t.snapshot.chunk_count} 个全文片段 · 调用 ${t.call_count||0} 次</p>`:'';$('taskBody').innerHTML=`<p><strong>${esc(t.status)}</strong></p>${meta}${t.error?`<p class="muted">${esc(t.error)}</p>`:''}${t.result?`<div class="task-result">${text(t.result)}</div>${t.type==='read'?'<button class="button" id="adopt">采用为正式精读卡</button>':''}`:''}`;if(t.result&&t.type==='read')$('adopt').onclick=async()=>{try{const d=await api(`/api/tasks/${id}/adopt`,{method:'POST'});state.selected=d.summary.citekey;await loadCards();toast('精读卡已采用，可以同步到 Zotero')}catch(e){toast(e.message)}};if(['排队','分析中'].includes(t.status))setTimeout(()=>poll(id),1200)}catch(e){$('taskBody').innerHTML=`<p>${esc(e.message)}</p>`}}
async function loadSettings(){try{const s=await api('/api/settings'),ai=s.ai;state.aiLocked=!!(ai.managed||ai.published);const box=$('aiManagedStatus');
if(ai.managed){box.hidden=false;$('aiManagedDot').classList.add('green');$('aiManagedLabel').textContent=`DeepSeek 已由服务端配置 · 模型 ${ai.model}`;$('aiEditableFields').hidden=true;$('aiConfigHint').textContent='API Key 保存在 Vercel 环境变量中，网页不需要也无法查看；如需更换请在 Vercel 修改 DEEPSEEK_API_KEY 后重新部署。';$('saveSettings').hidden=true;$('aiTestStatus').textContent='已配置，可直接使用'}
else if(ai.published){box.hidden=false;$('aiManagedDot').classList.remove('green');$('aiManagedLabel').textContent='DeepSeek 尚未配置';$('aiEditableFields').hidden=true;$('aiConfigHint').textContent='请在 Vercel 项目的 Environment Variables 添加 DEEPSEEK_API_KEY（可选 DEEPSEEK_MODEL、DEEPSEEK_BASE_URL），保存后重新部署即可长期生效。';$('saveSettings').hidden=true;$('aiTestStatus').textContent='未配置'}
else{$('aiBaseUrl').value=ai.base_url;$('aiModel').value=ai.model;if(ai.configured)$('aiTestStatus').textContent='已配置'}
const z=s.zotero;
if(z.mode==='web')connection(!!z.connected,z.connected?`Zotero Cloud 已连接 · ${z.collection_count} 个集合${z.writable?' · 可同步笔记':'（只读：请在 zotero.org/settings/keys 勾选 Allow write access）'}`:`Zotero Cloud 未连接：${z.error||'请检查 ZOTERO_USER_ID / ZOTERO_API_KEY'}`);
else connection(!z.error,z.error?'Zotero 未连接':`Zotero Desktop ${z.version||''} 已连接${z.writable?'，可同步笔记（Web API）':'；'+(z.web_api?.hint||'配置 Zotero Web API 后可同步笔记')}`)}catch(e){}}
async function saveSettings(){if(state.aiLocked)return toast('AI 已由服务端配置，无需在网页保存。');try{const r=await api('/api/settings/ai',{method:'PATCH',body:JSON.stringify({base_url:$('aiBaseUrl').value,model:$('aiModel').value,api_key:$('aiKey').value})});$('aiBaseUrl').value=r.base_url;$('aiTestStatus').textContent=r.configured?'已配置':'尚未配置';toast(r.notice||'AI 设置已保存')}catch(e){toast(e.message)}}
document.querySelectorAll('.nav-tab').forEach(x=>x.onclick=()=>showView(x.dataset.view));$('collectionSelect').onchange=async e=>{state.collection=e.target.value;localStorage.setItem('researchCollection',state.collection);state.selected=null;await loadCards()};$('searchInput').oninput=()=>{clearTimeout(window.timer);window.timer=setTimeout(loadCards,250)};$('statusFilter').onchange=loadCards;$('refreshButton').onclick=loadCards;$('compareSelected').onclick=()=>showView('compare');$('runCompareAI').onclick=()=>toast('AI 比较将在下一步接入具体研究问题。');$('openSettings').onclick=()=>$('settingsDialog').showModal();$('openSettingsSmall').onclick=()=>$('settingsDialog').showModal();$('saveSettings').onclick=saveSettings;$('testAI').onclick=async()=>{if(!state.aiLocked)await saveSettings();try{$('aiTestStatus').textContent=(await api('/api/settings/ai/test',{method:'POST'})).message}catch(e){toast(e.message)}};$('closeTask').onclick=()=>$('taskDrawer').classList.remove('open');$('generateDaily').onclick=generateDaily;$('dailyDateSelect').onchange=loadDaily;$('historyDateSelect').onchange=loadHistory;$('historySlotFilter').onchange=loadHistory;$('historyReadFilter').onchange=loadHistory;$('historyVenueInput').oninput=()=>{clearTimeout(window.historyTimer);window.historyTimer=setTimeout(loadHistory,300)};boot();
